# Generated by Django 3.0.3 on 2020-11-11 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_department', '0001_initial'),
        ('app_info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(default=0)),
                ('organizationalunit', models.CharField(blank=True, max_length=200)),
                ('positiontitle', models.CharField(max_length=200)),
                ('salarygrade', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('authorizedannualsalary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('actualannualsalary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('areacode', models.CharField(max_length=200)),
                ('areatype', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'Permanent'), ('2', 'Co-Terminus'), ('3', 'Elected')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_department.Department')),
            ],
            options={
                'ordering': ['positiontitle'],
            },
        ),
        migrations.CreateModel(
            name='Designationlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('date_appointed', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_designation.Plantilla')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField(default=datetime.datetime(2020, 11, 11, 9, 0, 33, 721797))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('plantilla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_designation.Plantilla')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contractual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiontitle', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Job Order', 'Job Order'), ('Project Based', 'Project Based')], max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_appointed', models.DateField(default=datetime.datetime(2020, 11, 11, 9, 0, 33, 723790))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_department.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
