# Generated by Django 2.1 on 2020-10-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_department', '0001_initial'),
        ('app_info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiontitle', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Job Order', 'Job Order'), ('Project Based', 'Project Based')], max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_appointed', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_department.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designationlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(default=0)),
                ('organizationalunit', models.CharField(blank=True, max_length=200)),
                ('positiontitle', models.CharField(max_length=200)),
                ('salarygrade', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('authorizedannualsalary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('actualannualsalary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('areacode', models.CharField(max_length=200)),
                ('areatype', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Permanent', 'Permanent'), ('Co-Terminus', 'Co-Terminus'), ('Elected', 'Elected')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_department.Department')),
            ],
            options={
                'ordering': ['positiontitle'],
            },
        ),
        migrations.AddField(
            model_name='designationlog',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_designation.Plantilla'),
        ),
        migrations.AddField(
            model_name='designationlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
        ),
        migrations.AddField(
            model_name='designation',
            name='plantilla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_designation.Plantilla'),
        ),
        migrations.AddField(
            model_name='designation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
        ),
    ]
