# Generated by Django 3.0.3 on 2020-11-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractual',
            name='date_appointed',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 64057)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='date_appointed',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 63060)),
        ),
    ]
