# Generated by Django 3.0.3 on 2020-11-21 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_designation', '0002_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractual',
            name='date_appointed',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 894183)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='date_appointed',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 892189)),
        ),
    ]
