# Generated by Django 3.0.3 on 2020-10-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_designation', '0002_auto_20201018_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='is_taken',
        ),
    ]
