# Generated by Django 3.0.3 on 2020-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtr',
            name='profile',
        ),
        migrations.AddField(
            model_name='dtr',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
