# Generated by Django 3.0.3 on 2020-11-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtr', '0003_dtr_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtr_assign',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='dtr',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dtr.Dtr_Assign'),
        ),
        migrations.AlterField(
            model_name='dtr_assign',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
