# Generated by Django 3.0.3 on 2020-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
