# Generated by Django 3.0.3 on 2020-12-08 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_hris', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='settings',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
