# Generated by Django 3.0.3 on 2020-12-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hris', '0003_auto_20201208_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='budget_name',
            field=models.CharField(default='Lymarie A. Malicdem', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='budget_title',
            field=models.CharField(default='Municipal Budget Officer', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='treasury_name',
            field=models.CharField(default='Jerry I. Fillalan', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='treasury_title',
            field=models.CharField(default='Municipal Treasury Officer', max_length=200),
        ),
    ]
