# Generated by Django 3.0.3 on 2020-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0003_rating_success_indicator_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
