# Generated by Django 3.0.3 on 2020-11-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0004_year_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='indicator',
            field=models.ManyToManyField(blank=True, to='app_performance_management.Success_Indicator'),
        ),
    ]
