# Generated by Django 3.0.3 on 2020-11-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0005_accomplishment_indicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='individual',
            new_name='accomplishment',
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
