# Generated by Django 3.0.3 on 2020-11-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0006_auto_20201121_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='success_indicator',
            options={'ordering': ('description',)},
        ),
        migrations.AlterField(
            model_name='rating',
            name='accomplishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Accomplishment'),
        ),
    ]
