# Generated by Django 3.0.3 on 2020-11-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_auto_20201121_1156'),
        ('app_performance_management', '0008_auto_20201121_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Accomplishment_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField(default=0)),
                ('remarks', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Year')),
            ],
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='accomplishment_rating',
            field=models.ManyToManyField(blank=True, to='app_performance_management.Accomplishment_Rating'),
        ),
    ]
