# Generated by Django 3.0.3 on 2020-11-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_auto_20201121_1156'),
        ('app_performance_management', '0010_auto_20201121_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_accomplishment', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField(default=0)),
                ('remarks', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('actual_accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Actual_Accomplishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='accomplishment_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='actual_accomplishment',
            name='accomplishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Accomplishment'),
        ),
        migrations.AddField(
            model_name='actual_accomplishment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
        ),
        migrations.AddField(
            model_name='actual_accomplishment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Year'),
        ),
    ]
