# Generated by Django 3.0.3 on 2020-11-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0011_auto_20201122_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accomplishment_Rating',
        ),
    ]
