# Generated by Django 3.0.3 on 2020-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0012_delete_accomplishment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_accomplishment',
            name='accomplishment',
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='actual_accomplishment',
            field=models.ManyToManyField(blank=True, to='app_performance_management.Actual_Accomplishment'),
        ),
    ]
