# Generated by Django 3.0.3 on 2020-11-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0013_auto_20201122_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='actual_accomplishment',
        ),
        migrations.AddField(
            model_name='actual_accomplishment',
            name='accomplishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Accomplishment'),
            preserve_default=False,
        ),
    ]
