# Generated by Django 3.0.3 on 2020-11-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0014_auto_20201122_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_accomplishment',
            old_name='user',
            new_name='profile',
        ),
    ]
