# Generated by Django 3.0.3 on 2020-11-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_performance_management', '0016_auto_20201122_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_accomplishment',
            name='accomplishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Accomplishment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating_accomplishment',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_performance_management.Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating_accomplishment',
            name='actual_accomplishment',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Actual_Accomplishment',
        ),
    ]
