# Generated by Django 3.0.3 on 2020-11-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_profile', '0001_initial'),
        ('dtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan_Attendace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
    ]
