# Generated by Django 3.0.3 on 2020-11-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_profile', '0001_initial'),
        ('dtr', '0002_scan_attendace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_attendace',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile'),
        ),
    ]
