# Generated by Django 3.0.3 on 2020-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='form',
            field=models.FileField(default=1, upload_to='forms/'),
            preserve_default=False,
        ),
    ]
