# Generated by Django 3.0.3 on 2020-11-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='form',
            new_name='file',
        ),
    ]
