# Generated by Django 3.0.3 on 2020-10-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0002_retired'),
        ('app_rewards_recognitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward_Recognitions',
            new_name='Rewards_Recognitions',
        ),
    ]
