# Generated by Django 3.0.3 on 2020-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', to='app_info_profile.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
