# Generated by Django 3.0.3 on 2020-10-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0004_auto_20201026_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
    ]
