# Generated by Django 3.0.3 on 2020-11-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deducted_transaction',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 68045)),
        ),
        migrations.AlterField(
            model_name='deducted_transaction',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 68045)),
        ),
    ]
