# Generated by Django 3.0.3 on 2020-10-24 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transaction', '0002_rejected_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('leave_type', models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset')], max_length=50)),
                ('days', models.DecimalField(decimal_places=3, default=0, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deducted_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('leave_type', models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset')], max_length=50)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default=1, max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deducted_Action_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=3, default=0, max_digits=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deducted_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transaction.Deducted_Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rejected_log',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transaction.Deducted_Transaction'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
