# Generated by Django 3.0.3 on 2020-10-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0003_auto_20201024_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_Generated_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('leave_type', models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset')], max_length=50)),
                ('days', models.DecimalField(decimal_places=3, default=0, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='rejected_log',
            old_name='transaction',
            new_name='deducted_transaction',
        ),
    ]
