# Generated by Django 3.0.3 on 2020-10-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0006_auto_20201024_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejected_transaction',
            name='deducted_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transaction.Deducted_Transaction'),
        ),
    ]
