# Generated by Django 3.0.3 on 2020-10-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0009_batch_generated_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch_generated_transaction',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='generated_transaction',
            old_name='description',
            new_name='remarks',
        ),
    ]
