# Generated by Django 3.0.3 on 2020-11-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_internet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ticket', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='reason',
        ),
        migrations.AddField(
            model_name='voucher',
            name='generate_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_internet.Generate_Ticket'),
            preserve_default=False,
        ),
    ]
