# Generated by Django 3.0.3 on 2020-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_internet', '0003_auto_20201122_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_ticket',
            name='no_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
