# Generated by Django 3.0.3 on 2020-11-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_internet', '0005_mikrotik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mikrotik',
            old_name='user_limit_update',
            new_name='user_limit_uptime',
        ),
    ]
