# Generated by Django 3.0.3 on 2020-12-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tips_person', '0003_auto_20201216_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Recommended_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_assistance', models.CharField(choices=[('1', 'Counseling'), ('2', 'Legal Assistance (Retainer Lawyer/Others)'), ('3', 'Referral'), ('4', 'Financial Assistance'), ('5', 'Material Assistance'), ('6', 'Others')], max_length=50)),
                ('specify', models.CharField(blank=True, max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_person.Tips_Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_nature_of_services.Tips_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Recommended_Services_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('mode_assistance', models.CharField(choices=[('1', 'Cash'), ('2', 'Check')], max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_nature_of_services.Tips_Category')),
                ('recommended_services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tips_nature_of_services.Tips_Recommended_Services')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_nature_of_services.Tips_Sub_Category')),
            ],
        ),
    ]
