# Generated by Django 3.0.3 on 2020-12-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_nature_of_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips_recommended_services',
            name='specify',
            field=models.CharField(max_length=200),
        ),
    ]
