# Generated by Django 3.0.3 on 2020-12-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_nature_of_services', '0002_auto_20201217_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips_recommended_services',
            name='services_assistance',
            field=models.CharField(choices=[('1', 'Counseling'), ('2', 'Legal Assistance (Retainer Lawyer/Others)'), ('3', 'Referral'), ('4', 'Other Services Assistance')], max_length=50),
        ),
    ]
