# Generated by Django 3.0.3 on 2020-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0002_auto_20201209_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_background',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
