# Generated by Django 3.0.3 on 2020-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0003_auto_20201210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='rating',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
