# Generated by Django 3.0.3 on 2021-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0004_auto_20201210_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_background',
            name='period_from',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='educational_background',
            name='period_to',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='government_other_info',
            name='date_issued',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='government_other_info',
            name='id_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='government_other_info',
            name='issued_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references3',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references3',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references3',
            name='tel_no',
            field=models.CharField(max_length=200),
        ),
    ]
