# Generated by Django 3.0.7 on 2021-01-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0004_auto_20201210_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_background',
            name='period_from',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='educational_background',
            name='period_to',
            field=models.IntegerField(default=2021),
        ),
    ]
