# Generated by Django 3.0.3 on 2021-01-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0005_auto_20210128_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_background',
            name='spouse_government_date_issued',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
