# Generated by Django 3.0.7 on 2021-02-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0005_auto_20210125_1317'),
        ('pds', '0006_auto_20210129_2123'),
    ]

    operations = [
    ]
