# Generated by Django 2.1 on 2020-10-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('nohrs', models.IntegerField(default=0)),
                ('typeofld', models.CharField(choices=[('Managerial', 'Managerial'), ('Supervisory', 'Supervisory'), ('Technical', 'Technical')], max_length=100)),
                ('sponsoredby', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
