# Generated by Django 3.0.3 on 2020-11-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_pds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 51094)),
        ),
        migrations.AlterField(
            model_name='learning_development',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 25162)),
        ),
        migrations.AlterField(
            model_name='learning_development',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 25162)),
        ),
        migrations.AlterField(
            model_name='voluntary_work',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 55081)),
        ),
        migrations.AlterField(
            model_name='voluntary_work',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 55081)),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 54084)),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 16, 9, 38, 54084)),
        ),
    ]
