# Generated by Django 2.1 on 2020-10-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0001_initial'),
        ('app_201_pds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spousesurname', models.CharField(blank=True, max_length=200)),
                ('spousefirstname', models.CharField(blank=True, max_length=200)),
                ('spousemiddlename', models.CharField(blank=True, max_length=200)),
                ('spouseextname', models.CharField(blank=True, max_length=200)),
                ('spouseoccupation', models.CharField(blank=True, max_length=200)),
                ('spouseemployer', models.CharField(blank=True, max_length=200)),
                ('spouseemployeraddress', models.CharField(blank=True, max_length=200)),
                ('spousetelephone', models.CharField(blank=True, max_length=200)),
                ('spouse_government_issued_id', models.CharField(blank=True, max_length=200)),
                ('spouse_government_id_no', models.CharField(blank=True, max_length=200)),
                ('spouse_government_date_issued', models.DateField(blank=True, null=True)),
                ('fathersurname', models.CharField(blank=True, max_length=200)),
                ('fatherfirstname', models.CharField(blank=True, max_length=200)),
                ('fathermiddlename', models.CharField(blank=True, max_length=200)),
                ('fatherextname', models.CharField(blank=True, max_length=200)),
                ('mothersurname', models.CharField(blank=True, max_length=200)),
                ('motherfirstname', models.CharField(blank=True, max_length=200)),
                ('mothermiddlename', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_question1', models.BooleanField(default=False)),
                ('label1', models.CharField(blank=True, max_length=30)),
                ('is_question2', models.BooleanField(default=False)),
                ('label2', models.CharField(blank=True, max_length=30)),
                ('is_question3', models.BooleanField(default=False)),
                ('label3', models.CharField(blank=True, max_length=30)),
                ('is_question4', models.BooleanField(default=False)),
                ('label4', models.CharField(blank=True, max_length=30)),
                ('is_question5', models.BooleanField(default=False)),
                ('label5', models.CharField(blank=True, max_length=30)),
                ('is_question6', models.BooleanField(default=False)),
                ('label6', models.CharField(blank=True, max_length=30)),
                ('is_question7', models.BooleanField(default=False)),
                ('label7', models.CharField(blank=True, max_length=30)),
                ('is_question8', models.BooleanField(default=False)),
                ('label8', models.CharField(blank=True, max_length=30)),
                ('is_question9', models.BooleanField(default=False)),
                ('label9', models.CharField(blank=True, max_length=30)),
                ('is_question10', models.BooleanField(default=False)),
                ('label10', models.CharField(blank=True, max_length=30)),
                ('is_question11', models.BooleanField(default=False)),
                ('label11', models.CharField(blank=True, max_length=30)),
                ('is_question12', models.BooleanField(default=False)),
                ('label12', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
