# Generated by Django 3.0.3 on 2020-11-21 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_pds', '0002_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 886205)),
        ),
        migrations.AlterField(
            model_name='learning_development',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 868402)),
        ),
        migrations.AlterField(
            model_name='learning_development',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 868402)),
        ),
        migrations.AlterField(
            model_name='voluntary_work',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 888199)),
        ),
        migrations.AlterField(
            model_name='voluntary_work',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 888199)),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 887202)),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 887202)),
        ),
    ]
