# Generated by Django 2.1 on 2020-10-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0001_initial'),
        ('app_201_pds', '0002_familybackground_otherinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencesname1', models.CharField(blank=True, max_length=200)),
                ('referencesaddress1', models.CharField(blank=True, max_length=200)),
                ('referencestel1', models.CharField(blank=True, max_length=200)),
                ('referencesname2', models.CharField(blank=True, max_length=200)),
                ('referencesaddress2', models.CharField(blank=True, max_length=200)),
                ('referencestel2', models.CharField(blank=True, max_length=200)),
                ('referencesname3', models.CharField(blank=True, max_length=200)),
                ('referencesaddress3', models.CharField(blank=True, max_length=200)),
                ('referencestel3', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
