# Generated by Django 3.0.3 on 2020-11-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        ('app_201_pds', '0004_auto_20201022_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_background',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
            preserve_default=False,
        ),
    ]
