# Generated by Django 3.0.3 on 2020-11-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_pds', '0006_auto_20201102_0023'),
    ]

    operations = [

    ]
