# Generated by Django 3.0.3 on 2020-11-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        ('app_201_pds', '0007_auto_20201102_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_information',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile'),
            preserve_default=False,
        ),
    ]
