# Generated by Django 3.0.3 on 2020-11-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        ('app_201_pds', '0009_children_educational_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_service', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_of_examination', models.DateField(blank=True, null=True)),
                ('place_of_examination', models.CharField(blank=True, max_length=200)),
                ('examinee_number', models.IntegerField(default=0)),
                ('date_of_validity', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
