# Generated by Django 3.0.3 on 2020-11-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_pds', '0013_auto_20201104_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
