# Generated by Django 3.0.3 on 2020-11-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0007_delete_retired'),
        ('app_201_pds', '0015_auto_20201104_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('question_2', models.BooleanField(default=False)),
                ('detail_2', models.CharField(blank=True, max_length=30)),
                ('question_3', models.BooleanField(default=False)),
                ('detail_3', models.CharField(blank=True, max_length=30)),
                ('question_4', models.BooleanField(default=False)),
                ('detail_4', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q39',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('question_2', models.BooleanField(default=False)),
                ('detail_2', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q37',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q35',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('question_2', models.BooleanField(default=False)),
                ('detail_2', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Q34',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=False)),
                ('detail_1', models.CharField(blank=True, max_length=30)),
                ('question_2', models.BooleanField(default=False)),
                ('detail_2', models.CharField(blank=True, max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
