# Generated by Django 3.0.3 on 2020-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_pds', '0017_references1_references2_references3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references1',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references1',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references1',
            name='tel_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references2',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references2',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references2',
            name='tel_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='references3',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='references3',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='references3',
            name='tel_no',
            field=models.CharField(max_length=30),
        ),
    ]
