# Generated by Django 3.0.3 on 2020-11-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0007_delete_retired'),
        ('app_201_pds', '0018_auto_20201107_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government_Other_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_id', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=30)),
                ('date_issued', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
