# Generated by Django 3.0.3 on 2020-11-11 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designate', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('station', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('lwabs', models.CharField(max_length=200)),
                ('separtion_date', models.CharField(max_length=200)),
                ('date_from', models.DateField(default=datetime.datetime(2020, 11, 11, 9, 0, 33, 718803))),
                ('date_to', models.DateField(default=datetime.datetime(2020, 11, 11, 9, 0, 33, 718803))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_info_profile.Profile')),
            ],
        ),
    ]
