# Generated by Django 3.0.3 on 2020-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0004_remove_profile_url_unique'),
        ('app_201_service_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRecord',
            new_name='Service_Record',
        ),
    ]
