# Generated by Django 3.0.3 on 2020-11-21 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_201_service_records', '0002_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_record',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 889197)),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 32, 15, 889197)),
        ),
    ]
