# Generated by Django 3.0.3 on 2020-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_administrator',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
