# Generated by Django 3.0.3 on 2020-11-24 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designate', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('station', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('lwabs', models.CharField(max_length=200)),
                ('separtion_date', models.CharField(max_length=200)),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
    ]
