# Generated by Django 3.0.3 on 2020-12-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips_administrator',
            name='is_dwsd_admin',
            field=models.BooleanField(default=False),
        ),
    ]
