# Generated by Django 3.0.3 on 2020-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiling', '0002_tips_administrator_is_dwsd_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips_administrator',
            name='is_agriculture_admin',
            field=models.BooleanField(default=False),
        ),
    ]
