# Generated by Django 3.0.3 on 2020-10-22 02:21

import app_info_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0002_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_unique',
            field=models.CharField(default="", max_length=200),
        ),
    ]
