# Generated by Django 3.0.3 on 2020-11-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info_profile', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retired',
        ),
    ]
