# Generated by Django 3.0.7 on 2021-01-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20201216_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deducted_transaction',
            name='leave_type',
            field=models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset'), ('5', 'Maternity Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generated_transaction',
            name='leave_type',
            field=models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset'), ('5', 'Maternity Leave')], max_length=50),
        ),
    ]
