# Generated by Django 3.0.7 on 2021-02-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210125_1317'),
        ('transaction', '0004_auto_20210128_1648'),
    ]

    operations = [
    ]
