# Generated by Django 3.0.7 on 2021-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_merge_20210203_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deducted_transaction',
            name='leave_type',
            field=models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset'), ('5', 'Maternity Leave'), ('6', 'Faternity Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generated_transaction',
            name='leave_type',
            field=models.CharField(choices=[('1', 'Sick Leave'), ('2', 'Vacation Leave'), ('3', 'Special Leave'), ('4', 'Offset'), ('5', 'Maternity Leave'), ('6', 'Faternity Leave')], max_length=50),
        ),
    ]
