# Generated by Django 3.0.7 on 2021-02-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210203_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='deducted_transaction',
            name='sick',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='deducted_transaction',
            name='vacation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
    ]
