# Generated by Django 3.0.3 on 2021-01-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saln_Relatives_In_The_Government_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_relative', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('name_of_agency', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Saln_Real_Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, max_length=200)),
                ('exact_location', models.CharField(blank=True, max_length=200)),
                ('assessed_value', models.CharField(blank=True, max_length=200)),
                ('current_fair_market_value', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('mode', models.CharField(blank=True, max_length=200)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Saln_Personal_Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Saln_Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=200)),
                ('name_of_creditors', models.CharField(blank=True, max_length=200)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Saln_Filling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling_type', models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Separated', 'Separated'), ('Not Applicable', 'Not Applicable')], max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Saln_Business_Interest_Financial_Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_enterprise', models.CharField(max_length=200)),
                ('business_address', models.CharField(blank=True, max_length=200)),
                ('nature_of_business', models.CharField(blank=True, max_length=200)),
                ('date_of_acquisition_of_interest', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
        ),
    ]
