# Generated by Django 3.0.3 on 2020-11-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_function_output', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Success_Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Rating_Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_accomplishment', models.CharField(max_length=200)),
                ('ratings', models.FloatField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_management.Accomplishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_management.Year')),
            ],
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='indicator',
            field=models.ManyToManyField(blank=True, to='performance_management.Success_Indicator'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_profile.Profile'),
        ),
    ]
