# Generated by Django 3.0.3 on 2020-11-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0002_auto_20201127_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semister',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='rating_accomplishment',
            old_name='semister',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semister',
            new_name='semester',
        ),
    ]
