# Generated by Django 3.0.3 on 2020-12-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0003_auto_20201127_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='success_indicator',
            options={'ordering': ('-description',)},
        ),
    ]
