# Generated by Django 3.0.3 on 2020-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0004_auto_20201211_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='core_function_output',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rating_accomplishment',
            name='actual_accomplishment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='success_indicator',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
