# Generated by Django 3.0.3 on 2020-12-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips_Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_code', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay_description', models.CharField(max_length=255)),
                ('region_code', models.IntegerField()),
                ('province_code', models.IntegerField()),
                ('city_municipality_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips_City_Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_code', models.CharField(max_length=255)),
                ('city_municipality_code', models.IntegerField()),
                ('city_municipality_description', models.CharField(max_length=255)),
                ('region_code', models.IntegerField()),
                ('province_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_code', models.CharField(max_length=255)),
                ('province_description', models.CharField(max_length=255)),
                ('region_code', models.IntegerField()),
                ('province_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_code', models.CharField(max_length=255)),
                ('region_description', models.CharField(max_length=255)),
                ('region_code', models.IntegerField()),
            ],
        ),
    ]
