# Generated by Django 3.0.3 on 2020-12-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips_barangay',
            name='barangay_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
