# Generated by Django 3.0.3 on 2020-12-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips_address', '0002_auto_20201212_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips_barangay',
            old_name='barangay_code',
            new_name='barangay_name',
        ),
        migrations.RenameField(
            model_name='tips_city_municipality',
            old_name='city_municipality_description',
            new_name='city_municipality_name',
        ),
        migrations.RenameField(
            model_name='tips_province',
            old_name='province_description',
            new_name='province_name',
        ),
        migrations.RenameField(
            model_name='tips_region',
            old_name='psgc_code',
            new_name='region_name',
        ),
        migrations.RemoveField(
            model_name='tips_barangay',
            name='barangay_description',
        ),
        migrations.RemoveField(
            model_name='tips_barangay',
            name='city_municipality_code',
        ),
        migrations.RemoveField(
            model_name='tips_barangay',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='tips_barangay',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='tips_city_municipality',
            name='city_municipality_code',
        ),
        migrations.RemoveField(
            model_name='tips_city_municipality',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='tips_city_municipality',
            name='psgc_code',
        ),
        migrations.RemoveField(
            model_name='tips_city_municipality',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='tips_province',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='tips_province',
            name='psgc_code',
        ),
        migrations.RemoveField(
            model_name='tips_province',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='tips_region',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='tips_region',
            name='region_description',
        ),
        migrations.AddField(
            model_name='tips_barangay',
            name='city_municipality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_City_Municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tips_city_municipality',
            name='province',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tips_province',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_Region'),
            preserve_default=False,
        ),
    ]
