# Generated by Django 3.0.3 on 2020-11-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_settings', '0002_auto_20201102_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='dtr_from',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='dtr_to',
        ),
    ]
