# Generated by Django 3.0.3 on 2020-12-11 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tips_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(blank=True, max_length=200)),
                ('ext_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=10)),
                ('civil_status', models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Widowed'), ('4', 'Separated'), ('5', 'Annulled')], max_length=10)),
                ('philhealth', models.CharField(blank=True, max_length=200)),
                ('religion', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=200)),
                ('highest_educational_attainment', models.CharField(blank=True, max_length=200)),
                ('skills_occupation', models.CharField(blank=True, max_length=200)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tips_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_Barangay')),
                ('city_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_City_Municipality')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tips_person.Tips_Person')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_Province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips_address.Tips_Region')),
            ],
        ),
    ]
