# Generated by Django 3.0.3 on 2020-12-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips_address',
            name='purok_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
